name: geocoder
description: Forward and reverse geocoding.
version: 0.3.1
homepage: https://github.com/aloisdeniel/flutter_geocoder

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.aloisdeniel.geocoder
        pluginClass: GeocoderPlugin
      ios:
        pluginClass: GeocoderPlugin
